server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  zipkin:
    baseUrl: http://localhost:9411/
    discoveryClientEnabled: false
